### ISSUE TITLE
Argument of type'{ OnDrop: () => void; }' not assignable to parameter of type DropzoneOptions

### ISSUE THREAD

**Issue by MikeGitIt** [bmvantunes/youtube-2021-feb-multiple-file-upload-formik#1]
I am seeing the following error for some unfamiliar reason.

`Argument of type '{ onDrop: (accFiles: any, rejFiles: any) => void; accept: string[]; maxSize: number; }' is not assignable to parameter of type 'DropzoneOptions'.
  Type '{ onDrop: (accFiles: any, rejFiles: any) => void; accept: string[]; maxSize: number; }' is missing the following properties from type 'Pick<any, PropTypes>': multiple, onDragEnter, onDragOver, onDragLeavets(2345)`

**Comment by bmvantunes** [comment]
I did the following: 

```
git clone https://github.com/bmvantunes/youtube-2021-feb-multiple-file-upload-formik.git
cd youtube-2021-feb-multiple-file-upload-formik\
npm install
npm run build
```

I see no errors... Do you see errors doing that? :)

**Comment by MikeGitIt** [comment]
I am starting from scratch and not running the finished version - I am inside the starting point branch.  May very well be something to do with my .npmrc file setup. I dunno for sure but I will figure it out. You can close this issue, if you wish.

**Comment by bmvantunes** [comment]
I can't replicate your error. Can you share your repository? :)
